# Physical constants
eps_0: 1.0    # 8.854           # Electric permittivity of free space [F/m]
eps_r: 1.0    # 1.0006          # Relative permittivity

# Data
Ve: null   # (*)             # Electric potential [V] at the emitter
Vc: null      # (*)             # Electric potential [V] at the collector
RHS_EXPRESSION: null

# Set-up configurations
PATH_TO_MESH: ../mesh/LogCircular_1_100-B.msh
NUM_CONCENTRIC_REF: 0
LOAD_FROM_SETUP: 5                  # Setups: mesh, analytical solution, forcing term
# Options: 0: NONE (**)
#          1: CurvedRidges (from step-14)
#          2: Exercise_2_3 (from step-14)
#          3: Rectangle_1_99 (**) (modified step-14 with 1:99 ratio)
#          4: LogCircular_1_10
#          5: LogCircular_1_100

# Framework configuration
MANUAL_LIFTING_ON: 1       # 0: OFF, 1: ON,
REFINEMENT_CRITERION: 1    # 1: global_refinement, 2: dual_weighted_error_estimator
DUAL_FUNCTIONAL: 2         # 1: point_evaluation,  2: flux_evaluation

# Point coordinates
EVALUATION_POINT_X: 0.019375
EVALUATION_POINT_Y: 0.

# Reference values
EXACT_POINT_VALUE: 3148.182801
EXACT_FLUX: 2.728752707684e+04

# Mesh refinement options:
REFINEMENT_STRATEGY: 1      # 1. fixed_fraction(default), 2. fixed_number, 3. optimize
TOP_FRACTION: 0.80          # default: 0.8
BOTTOM_FRACTION: 0.01       # default: 0.02
OPTIMIZE_ORDER: null        # default: 2

MANIFOLD_IS_APPLIED: 2      # 0: no, 1: yes, 2: on bdry Flat Manif otw, 3: on bdry TransfiniteManif otw


# NOTES:
# (*): Will be overridden by the choice of a predefined Setup
# (**): PATH_TO_MESH must be specified.
#       If there isn't (**), PATH_TO_MESH is predetermined by setup