# Physical constants
eps_0: 1.0    # 8.854           # Electric permittivity of free space [F/m]
eps_r: 1.0    # 1.0006          # Relative permittivity


# Set-up configurations
PATH_TO_MESH: ../mesh/myWWdelaunay3.msh
LOAD_FROM_SETUP: 11
# Options: 0:  NONE                  (**)
#          2:  deal.ii's step-14
#          5:  LogCircular_1_100     (**)
#          10: LogCircular_1_2       (**)
#          11: Wire Wire             (**)
#          ------- not for custom use -------------------------------
#          1, 3, 4, 6, 7, 8, 9: Specific test cases to be ignored


# Boundary data (***)
Ve: 20000   # (***)          # Electric potential [V] at the emitters: Boundary IDs 1.2
Vc: 0       # (***)          # Electric potential [V] at the collectors: Boundary IDs 3,4


# Framework configuration
MAPPING_DEGREE: 2
MANUAL_LIFTING_ON: 1       
# Options: 0: OFF 
#          1: ON
REFINEMENT_CRITERION: 2    
# Options: 1: Global refinements
#          2: Dual-weighted goal-oriented error estimator
#          3: Global refinements but perform dual weighted estimation
#          ------- not for custom use -------------------------------
#          4: Only refine first ring of cells around the emitter
DUAL_FUNCTIONAL: 2         
# Options: 1: Value in a point (set below) [only in serial code]
#          2: Minus flux around the emitter
MAX_DEGREES_OF_FREEDOM: 1.e6

# Point coordinates
EVALUATION_POINT_X: none
EVALUATION_POINT_Y: none

# Reference values
EXACT_POINT_VALUE: none
EXACT_FLUX: none

MANIFOLD_IS_APPLIED: 0
# Options: 0: no manifold description imposed
#          ------- not for custom use -----------------
#          1: everywhere
#          2: only on boundary
#          3: only on boundary with TransfiniteManifold

# NOTES:
# (**): PATH_TO_MESH must be specified.
#       If there isn't (**), PATH_TO_MESH is predetermined by setup
# (***): Only for SETUP 11. 
#        Will be otherwise overridden by the choice of a predefined setup's boundary function.
